services:
    caddy:
        image: caddy:2.8.4-alpine
        restart: unless-stopped
        pull_policy: missing
        cap_add:
            - NET_ADMIN
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./CaddyfileDevelopment:/etc/caddy/CaddyfileDevelopment
            - ./CaddyfileProduction:/etc/caddy/CaddyfileProduction
            - ./caddy_data:/data
            - ./caddy_config:/config
        networks:
            - shared

networks:
    shared:
        driver: bridge